version: '3.8'

services:
  app:
    # Construye la imagen Docker de la aplicación desde el Dockerfile en el directorio actual
    build: .
    # Mapea el puerto 8000 del contenedor al puerto 8000 en tu máquina local
    ports:
      - "8000:8000"
    # Monta volúmenes para persistir la base de datos y los archivos de audio temporales
    volumes:
      # Monta el directorio actual del proyecto en /app dentro del contenedor
      - .:/app
      # Monta la base de datos app.db para persistencia
      - app_db_data:/app/app.db
      # Monta el directorio temp_audio para persistencia de archivos de audio
      - temp_audio_data:/app/temp_audio
    # Reinicia el contenedor si se detiene inesperadamente
    restart: always
    # Ejecuta comandos antes de iniciar la aplicación principal
    # Primero, ejecuta las migraciones de Alembic
    # Luego, inicia la aplicación Uvicorn
    command: >
      bash -c "alembic upgrade head &&
               uvicorn main:app --host 0.0.0.0 --port 8000"
    # Carga variables de entorno desde el archivo .env (si lo usas)
    env_file:
      - .env

# Define los volúmenes persistentes
volumes:
  app_db_data:
  temp_audio_data:
