version: '3.8'

services:
  app:
    build: . # Construye la imagen usando el Dockerfile en el directorio actual
    ports:
      - "8000:8000" # Mapea el puerto 8000 del host al puerto 8000 del contenedor
    volumes:
      # Monta tu directorio actual del host en /app dentro del contenedor para desarrollo.
      - .:/app 
      # Monta un volumen persistente para la base de datos SQLite.
      # Esto asume que tu app.db se crea o se espera que esté en /app/app.db
      - db_data:/app/app.db # <--- MUY IMPORTANTE PARA LA PERSISTENCIA DE SQLite
    env_file: # <--- NUEVA LÍNEA: carga variables de entorno desde .env
      - .env
    environment:
      # Puedes mantener variables de entorno aquí si no quieres que estén en .env
      # o si son para desarrollo solamente.
      PYTHONUNBUFFERED: 1 # Útil para ver logs de Python en tiempo real
      # WHISPER_MODEL_DIR: /app/models # Si necesitas un directorio específico para los modelos de Whisper
    restart: unless-stopped # Reinicia el contenedor a menos que se detenga manualmente
    
# Define el volumen para la persistencia de la base de datos
volumes:
  db_data: # Este es un volumen nombrado por Docker, los datos se almacenarán en el sistema de archivos de Docker