version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - db_data:/app/database_volume_data
      - whisper_cache:/app/cache
    env_file:
      - .env
    environment:
      DATABASE_URL: "sqlite:////app/database_volume_data/app.db"
      PYTHONUNBUFFERED: "1"
      XDG_CACHE_HOME: /app/cache
      LANGUAGE_TOOL_URL: "http://languagetool:8010/v2/"
      # LANGUAGE_TOOL_PYTHON_CACHE_DIR no es necesario con el servidor externo
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - languagetool
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  languagetool:
    image: erikvl87/languagetool:latest
    ports:
      - "8010:8010"
    volumes:
      - languagetool_data:/languagetool/data
    restart: unless-stopped

volumes:
  db_data:
  whisper_cache:
  languagetool_data:
