"""Add language column to audio_submissions

Revision ID: 6d22c99e8da4
Revises: 93c3eb534cfd
Create Date: 2025-06-10 15:36:02.354772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d22c99e8da4'
down_revision: Union[str, None] = '93c3eb534cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_submissions', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_submissions', 'language')
    # ### end Alembic commands ###
