"""Add created_at to VocabularyItem - FINAL MANUAL FIX

Revision ID: e537f26cc96c
Revises: fda95a2801b6
Create Date: 2025-06-10 17:34:14.175198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e537f26cc96c'
down_revision: Union[str, None] = 'fda95a2801b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # MODIFICA ESTA LÍNEA: QUITA EL 'server_default'
    op.add_column('vocabulary_items', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # AÑADE ESTA LÍNEA para actualizar los registros existentes (opcional si tu tabla está vacía)
    op.execute(sa.text("UPDATE vocabulary_items SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL"))

    # ### END Alembic commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabulary_items', 'created_at')
    # ### end Alembic commands ###
